### PR TITLE
Introduce isUndefined, deprecate defined

### PR DESCRIPTION
**Pull request by mgred**
#### Purpose (TL;DR) - mandatory
This PR introduces an assertion called `isUndefined` that passes when the given value is `undefined`. This also deprecates the `defined` assertion

#### Background (Problem in detail)  - optional

See #87 #89 

#### How to verify - mandatory
1. Check out this branch
2. `npm install`
3. `npm run test`

#### Checklist for author

- [x] `npm run lint` passes
- [x] References to standard library functions are [cached](https://github.com/sinonjs/sinon/pull/1523).

### CODE REVIEW

**Comment by mantoni** [comment]
I understand "deprecated" as "prints a warning when used, but works as before". You removed it 😏 

This is fine with me, it just makes it a necessity to replace all `defined` usages when upgrading while a warning allows to gradually introduce the change.

**Comment by mroderick** [comment]
> I understand "deprecated" as "prints a warning when used, but works as before".

That is my understanding too.

I'd much prefer to give people a gentle warning, than break their tests immediately.

Perhaps first we can move https://github.com/sinonjs/sinon/blob/master/lib/sinon/util/core/deprecated.js to https://github.com/sinonjs/commons and then use it from there?

**Comment by mgred** [comment]
> I understand "deprecated" as "prints a warning when used, but works as before". You removed it 😏
>
> This is fine with me, it just makes it a necessity to replace all `defined` usages when upgrading while a warning allows to gradually introduce the change.

🤦‍♂️ You're right! Showing a message is the way better option here 😅 

Do you think a simple `console.warn("This assertion will be deprecated with the next major version! Use assert.isUndefined instead");` is enough here?

Thanks a lot for your thoughts and review 👍

**Comment by mgred** [comment]
> > I understand "deprecated" as "prints a warning when used, but works as before".
> 
> That is my understanding too.

👍 

> I'd much prefer to give people a gentle warning, than break their tests immediately.
> 
> Perhaps first we can move https://github.com/sinonjs/sinon/blob/master/lib/sinon/util/core/deprecated.js t https://github.com/sinonjs/commons and then use it from there?

Cool, thanks for pointing that out. I will make a PR in the `@sinonjs/commons` package and will continue here as you guys suggested

Thank you very much 🙌

**Comment by mgred** [comment]
Cool 👍 

Just for documentation purpose. In https://github.com/sinonjs/referee/pull/93/files#diff-560744c83c3809c6fed70c6edc2d433dR11 We need to wrap everthing up because `assert` chaecks that the passed function has at least an arity of one and throws if not.

**Comment by mgred** [comment]
Oh I just merged 😕 and maybe a bit too fast? @mantoni anything from you side?

**Comment by mantoni** [comment]
No worries. This looks good to me 👌

**Comment by mroderick** [comment]
This has been published as `@sinonjs/referee@3.2.0`

**Pull request merged**
