### PR TITLE
Fix sinon match with referee

### PR DESCRIPTION
**Pull request by mantoni**
#### Purpose (TL;DR) - mandatory

In sinonjs/sinon#2498 `@sinonjs/samsam` was upgraded to v8 and this was released with sinon v15.0.2. This beaks a use case when `sinon.match` is used with referee assertions.

This PR adds a failing test, demonstrating the issue and upgrades samsam to v8 to fix it.

#### Background (Problem in detail)  - optional

The `isMatcher` helper in samsam checks whether the prototype of the given object is the matcher prototype (https://github.com/sinonjs/samsam/blob/main/lib/create-matcher/is-matcher.js). When there are two different versions of samsam in the dependency tree, there are two instances of that prototype. Therefore matcher detection fails if the matcher was created with the one version and the check is done with the other version of samsam.

#### Solution  - optional

There should always be exactly one version of samsam in the dependency tree.

#### How to verify - mandatory

1. Check out this branch
2. `npm install`
3. `npm test`

#### Checklist for author

- [x] `npm run lint` passes
- [x] References to standard library functions are [cached](https://github.com/sinonjs/sinon/pull/1523).

### CODE REVIEW

**Comment by fatso83** [comment]
The test seems a bit fragile when it depends on someone needing to keep two libraries in sync. Could we possibly change this for something that can handle different versions interacting? Say, check for a Symbol or something.

**Comment by mantoni** [comment]
That wouldn't help. If there are two versions of the library in the tree, the symbol would exist twice as well. We would need a global ...

**Comment by fatso83** [comment]
Could employ `Symbol.of("identifier")` for that? Just a glorified global constant, but is not enumerated or anything like that, so a bit better than the old ES5 approaches.

**Comment by mantoni** [comment]
That's a good idea. I like it!

**Comment by fatso83** [comment]
sure, I am not a blocker :)

**Pull request merged**
