### PR TITLE
Remove test helper from equals

### PR DESCRIPTION
**Pull request by khamiltonuk**
It was identified that the test helper is hard to maintain and understand

### CODE REVIEW

**Comment by khamiltonuk** [comment]
@mroderick I wasn't planning to add them, but I can
In my other pull requests I have removed refute from files

**Comment by mroderick** [comment]
> @mroderick I wasn't planning to add them, but I can

That would be great. `equals` is probably the most important assertion in the whole library.

> In my other pull requests I have removed refute from files

That's ok. At some point, I'd like to push for an effort of improving the tests by making sure that things are tested with bigger range of inputs and that all refutes are also tested.

**Comment by mroderick** [comment]
Ping @khamiltonuk ... can we work together on getting this one across the finish line?

**Review by mroderick — APPROVED** [review]
That was quite the pull request! 🥇 
Thank you for sticking with it @khamiltonuk

**Pull request merged**
